rle support added
trsvchn/coco-viewer pull request #59
Opened 2021-11-11 10:29 UTC by heada

I have impelmented support for uncompressed rle

2021-11-11 21:36 UTC, trsvchn commented
@heada Thank you for the PR!
But it looks like this PR reverts 2 previous commits: object based coloring and save file fix
could you please to try fix that!

2021-11-12 05:35 UTC, heada commented
@trsvchn check out my last commit. Tell me If something else incorrect.

2021-11-12 18:43 UTC, trsvchn commented
Thanks for the update! Going to try it locally!

2021-11-12 19:59 UTC, trsvchn requested changes
@heada Thanks for the PR and updates, I've tried it locally and it works. I left some comments, mostly some pycode style nits + some additional check for rle.

2021-11-12 19:59 UTC, trsvchn commented on cocoviewer.py
>  """COCO Dataset Viewer.
```suggestion
"""COCO Dataset Viewer.

```
Let's keep an empty line here.

2021-11-12 19:59 UTC, trsvchn commented on cocoviewer.py
> +import numpy as np
```suggestion

import numpy as np
```
nit: add an empty line to separate imports

2021-11-12 19:59 UTC, trsvchn commented on cocoviewer.py
>              # TODO: Fix problem with RLE
```suggestion
            # RLE mask for collection of objects (iscrowd=1)
```
nit: change comment

2021-11-12 19:59 UTC, trsvchn commented on cocoviewer.py
> +            elif isinstance(m, dict):
```suggestion
            elif isinstance(m, dict) and objects[i]["iscrowd"]:
```
According to [format-data](https://cocodataset.org/#format-data):
> The segmentation format depends on whether the instance represents a single object (iscrowd=0 in which case polygons are used) or a collection of objects (iscrowd=1 in which case RLE is used).

Let's check that here

2021-11-12 19:59 UTC, trsvchn commented on cocoviewer.py
> +  return img
```suggestion

def rle_to_mask(rle, height, width):
    rows, cols = height, width
    rle_pairs = np.array(rle).reshape(-1, 2)
    img = np.zeros(rows * cols, dtype=np.uint8)
    index_offset = 0

    for index, length in rle_pairs:
        index_offset += index
        img[index_offset:index_offset + length] = 255
        index_offset += length

    img = img.reshape(cols, rows)
    img = img.T
    return img

```
Python code style: let's use common python coding styles: snake case for var names, 4 spaces for indentation, spacing after `,`, 2 empty lines between high level functions definitions.

2021-11-12 19:59 UTC, trsvchn commented on cocoviewer.py
> +    main()
```suggestion
    main()

```
nit: newline at the end of a file

2021-11-16 06:45 UTC, heada commented
+ allright

2021-11-16 06:47 UTC, heada reviewed
allright

2021-11-17 13:03 UTC, trsvchn approved these changes
@heada LGTM! Many thanks for the PR!

2021-11-17 13:05 UTC, merged